spring:
  datasource:
    url: jdbc:sqlserver://90.158.106.204:14333;databaseName=BASurveyApp_Dev;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: developer
    password: Ba12345678+
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
jwt:
  secret: 546A576E5A7234753778214125442A472D4B6150645367566B58703273357638
# DBeaver, Microsoft sql server, SSMS 18
# "Server=90.158.106.204,14333; Database=BASurveyApp_Dev; User Id=developer; Password=Ba12345678+; TrustServerCertificate=True;"