#http://localhost/api/v1/swagger-ui/index.html
server:
  port: 80
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BASurveyDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
jwt:
  secret: 546A576E5A7234753778214125442A472D4B6150645367566B58703273357638
# DBeaver, Microsoft sql server, SSMS 18
# "Server=90.158.106.204,14333; Database=BASurveyApp_Dev; User Id=developer; Password=Ba12345678+; TrustServerCertificate=True;"