server:
  port: 80
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BASurveyDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: eralp
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
# DBeaver, Microsoft sql server, SSMS 18
# "Server=90.158.106.204,14333; Database=BASurveyApp_Dev; User Id=developer; Password=Ba12345678+; TrustServerCertificate=True;"