#http://localhost:8080/api/v1/swagger-ui/index.html
server:
  port: 8090
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:sqlserver://90.158.106.204:14333;databaseName=BASurveyApp_Dev;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: developer
    password: Ba12345678+
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
#  datasource:
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://34.27.37.245:5444/surveyAppDB
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hrmsapplicationteam1@gmail.com #Şifre hrms1234**
    password: mwwkmlzfpbfaweoq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enabled: true
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
jwt:
  secret: 546A576E5A7234753778214125442A472D4B6150645367566B58703273357638
# DBeaver, Microsoft sql server, SSMS 18
# "Server=90.158.106.204,14333; Database=BASurveyApp_Dev; User Id=developer; Password=Ba12345678+; TrustServerCertificate=True;"